# Generated by Django 3.0.3 on 2020-07-31 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='menu.Food')),
                ('monday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='menu.Food')),
                ('saturday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='menu.Food')),
                ('sunday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='menu.Food')),
                ('thursday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='menu.Food')),
                ('tuesday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='menu.Food')),
                ('wednesday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='menu.Food')),
                ('week_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
